graph TD
    A["fib(8)"]
    A --> B["fib(7)"]
    A --> C["fib(6)"]

    B --> D["fib(6)"]
    B --> E["fib(5)"]

    C --> F["fib(5)"]
    C --> G["fib(4)"]

    D --> H["fib(5)"]
    D --> I["fib(4)"]

    E --> J["fib(4)"]
    E --> K["fib(3)"]

    F --> L["fib(4)"]
    F --> M["fib(3)"]

    G --> N["fib(3)"]
    G --> O["fib(2)"]

    H --> P["fib(4)"]
    H --> Q["fib(3)"]

    I --> R["fib(3)"]
    I --> S["fib(2)"]

    J --> T["fib(3)"]
    J --> U["fib(2)"]

    K --> V["fib(2)"]
    K --> W["fib(1)"]

    L --> X["fib(3)"]
    L --> Y["fib(2)"]

    M --> Z["fib(2)"]
    M --> AA["fib(1)"]

    N --> BB["fib(2)"]
    N --> CC["fib(1)"]

    O --> DD["fib(1)"]
    O --> EE["fib(0)"]

    P --> FF["fib(3)"]
    P --> GG["fib(2)"]

    Q --> HH["fib(2)"]
    Q --> II["fib(1)"]

    R --> JJ["fib(2)"]
    R --> KK["fib(1)"]

    S --> LL["fib(1)"]
    S --> MM["fib(0)"]

    T --> NN["fib(2)"]
    T --> OO["fib(1)"]

    U --> PP["fib(1)"]
    U --> QQ["fib(0)"]

    V --> RR["fib(1)"]
    V --> SS["fib(0)"]

    X --> TT["fib(2)"]
    X --> UU["fib(1)"]

    Y --> VV["fib(1)"]
    Y --> WW["fib(0)"]

    Z --> XX["fib(1)"]
    Z --> YY["fib(0)"]

    BB --> ZZ["fib(1)"]
    BB --> AAA["fib(0)"]

    FF --> BBB["fib(2)"]
    FF --> CCC["fib(1)"]

    GG --> DDD["fib(1)"]
    GG --> EEE["fib(0)"]

    HH --> FFF["fib(1)"]
    HH --> GGG["fib(0)"]

    JJ --> HHH["fib(1)"]
    JJ --> III["fib(0)"]

    NN --> JJJ["fib(1)"]
    NN --> KKK["fib(0)"]

    TT --> LLL["fib(1)"]
    TT --> MMM["fib(0)"]

    BBB --> NNN["fib(1)"]
    BBB --> OOO["fib(0)"]
